;(setq company-idle-delay 0.3)
(require 'company)
(global-company-mode -1)
;(add-to-list 'company-backends 'company-cider)
;(add-to-list 'company-backends 'company-clang)
;(add-to-list 'company-backends 'company-capf)
